name: banggooseok
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    kakao_flutter_sdk:
    dio: 
    json_annotation:
    package_info:
    platform:
    shared_preferences:
    flutter_svg: ^0.21.0+1
    intl: ^0.17.0
    cupertino_icons: ^1.0.2
    retrofit:
    provider:
    carousel_slider:

dev_dependencies:
    flutter_test:
        sdk: flutter
    retrofit_generator:
    build_runner:
    json_serializable:

flutter:
    uses-material-design: true
    assets:
        - assets/svg/
        - assets/images/
        